var GAME_LEVELS = [
  [" x                                                                               x",
   " x                                       k    ooo                                x",
   " x                                    xxxxxxxxxxxxx                              x",
   " x                                   xx                                          x",
   " x                                xxxx                                           x",
   " x                             xxxx                                              x",
   " x     ooo   k                                                                   x",
   " xxxxxxxxxxxxxxx                                                                 x",
   " x                                                                               x",
   " x                                                                   ooo         x",
   " x                       ooo                              xxx      xxxxxx        x",
   " x                     xxxxxx                         xx    x!!!!!!x             x",
   " x                                 k               xxxx     xxxxxxxx             x",
   " x                                xxxxx        xxxxx               xo            x",
   " x                                                                 xxx           x",
   " x                                                            p                   x",
   " x  @                 ooo    ooo             k                p        k    ooo  x",
   " xxxxxxxxxxxxx  xxx  xxxxx  xxxxx      xxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxx",
   "             x  x x  x   x  x   x!!!!!!x               x!!!!!x                    ",
   "             x!!x x!!x   x!!x   x!!!!!!x               xxxxxxx                    ",
   "             xxxx xxxx   xxxx   x!!!!!!x                                          ",
   "                                xxxxxxxx                                          ",
   "                                                                                  ",
   "                                                                                  "],
  ["                                                                                                                                                                      ",
   "                            k  ooo                                              ",
   "                         xxxxxxxxxxxx                                           ",
   "                         x                                                      ",
   "                         x                                                      ",
   "                         x      s  ooo                                          ",
   "                         x     xxxxxxx                                          ",
   "                   ooo   x           x                                          ",
   "               xxxxxxxxxxx           xx                                         ",
   "   ooo k                                                                        ",
   "  xxxxxxx                                                                       ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                    xxxxx                                                       ",
   "                                        x!!!!!!!!x                              ",
   "                                        x!!!!!!!!x                              ",
   "     x    x                        ooo  x!!!!!!!!x ooo                          ",
   "     x!!!!x   xx                 xxxxxxxxxxxxxxxxxxxxxxxx                       ",
   "     x!!!!x                                                                     ",
   "     x!!!!x                                                                     ",
   "     x!!!!x     xx                                                              ",
   "     x!!!!x          ooo                                        ooo             ",
   "     x!!!!x         xxxxx                                       xxx             ",
   "     x!!!!!!!!!!!!!!!!!!x                                        p              ",
   "  @  x!!!!!!!!!!!!!!!!!!x      k     ooo      k           k      p         ooo  ",
   "xxxxxx!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                        ",
   "                                                                                                        ",
   "                                                                                                        ",
   "                                                                                                        ",
   "                                                                                                        ",
   "                                                                                                        ",
   "                                                                                                        ",
   "                                                                                                        ",
   "                                                                                                        ",
   "                                                                                                        ",
   "                                                                                                        ",
   "                                                                                                        ",
   "    k   ooo    k                k        k     k     k     k                                            ",
   " xxxxxxxxxxxxxxxxxxxx         xxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxx                              x",
   "                                   x   x                           x                                   x",
   "                                   x   x      ooo        ooo       x ooo                               x",
   "                                   x   x    xxxxxxxxxxxxxxxxxxxxxxxx                                   x",
   "                                   x   x                           x                                   x",
   "  ooo            k                 x   x  k                        x              ooo                  x",
   "  xxx         xxxxxxx              x   xxxxxxxxxxxxxxxxxxxxxxxxx   x                                   x",
   "    x!!!!!!!!!x                    xx  x                                                               x",
   "    xxxxxxxxxxx                    x   x                                                               x",
   "                                   x   x                                                               x",
   "                                   x   x  k   ooo               k     k      k     k       k           x",
   "                                   x   xxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      x",
   "   ooo            k                x   x                                                        x      x",
   "   xxx         xxxxxx              x   x                                                        x      x",
   "     x!!!!!!!!!x                   x  xx                                                        x      x",
   "     xxxxxxxxxxx                   x   x                                                        x      x",
   "                                   x   x  ooo    k    k    ooo    k    k    ooo    k   k        x      x",
   "                                   x   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       x  ooo x",
   "                                   x             x                                              x      x",
   "                                   x             x   ooo                                   ooo  x      x",
   "                                   xxxxx         x          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ooo x",
   "                                                 x                                              x      x",
   "                                                 x  k                                           x      x",
   "                                                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      x  ooo x",
   "                                                                                                x      x",
   "                                                                                                x      x",
   "                                                                                                x  ooo x",
   "                                                                                                x      x",
   "           k                 k              k            k            k          k      ooo     x      x",
   "        xxxxxxxx         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ooo x",
   "               x!!!!!!!!!x   p                                                                         x",
   "     @    ooo  x!!!!!!!!!x   p      ooo                 ooo               ooo                       s  x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
["                              ",
 "                              ",
 "      x   x xxxxx x   x       ",
 "      x   x x   x x   x       ",
 "      xxxxx x   x x   x       ",
 "        x   x   x x   x       ",
 "        x   xxxxx xxxxx       ",
 "                              ",
 "      x     x x xxxxx x       ",
 "      x     x x x   x x       ",
 "      x  x  x x x   x x       ",
 "      x  x  x x x   x         ",
 "      xxxxxxx x x   x x       ",
 "                              ",
 "                              ",
 "                              ",
 "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
   
   ];
                    


if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;